src/bin/ls-scenarios.cpp

That’s where antares-launcher is expecting it.

Send ls-scenarios output to stdout

---

.travis.yml
Makefile
include/config/dirs.hpp
scripts/antares-launcher
src/bin/ls-scenarios.cpp
src/config/dirs.cpp
src/config/linux-dirs.cpp
src/config/mac-dirs.cpp
src/config/test-dirs.cpp
src/glfw/main.cpp

* Allow `make run` without `make install`
* Test `make install` on Travis

Simplify running on Linux

---

src/sound/fx.cpp

Avoid accessing past end of sound array

---

src/game/minicomputer.cpp

Error was:
../../../src/game/minicomputer.cpp:887:5: error: no matching function for call to 'make_mini_screen'
make_mini_screen(
^~~~~~~~~~~~~~~~
../../../src/game/minicomputer.cpp:455:13: note: candidate template ignored: couldn't infer template argument
'size'
static void make_mini_screen(int16_t screen, const miniScreenLineType (&lines)[size]) {
^

Compilation bugfix 

---

src/sound/openal-driver.cpp

Fix music stereo mapping

---

src/mac/c/CocoaVideoDriver.m

Add NSFullScreenWindowMask on NSWindow

---

src/mac/c/CocoaVideoDriver.m

Not actually what I thought it was; should have tested first.

Revert "Add NSFullScreenWindowMask on NSWindow"

---

src/sound/openal-driver.cpp

Use 50% stereo separation

---

include/data/action.hpp
include/data/base-object.hpp
include/data/condition.hpp
include/data/enums.hpp
src/data/action.cpp
src/data/base-object.cpp
src/data/condition.cpp
src/game/action.cpp
src/game/condition.cpp

It’s easier to write docs for.

Change “object” back to “direct”

---

src/game/action.cpp
src/game/level.cpp
src/game/main.cpp
src/game/space-object.cpp

Likely doesn’t compile anymore

Remove DATA_COVERAGE code

---

src/bin/ls-scenarios.cpp

Print to stdout in antares-ls-scenarios

---

BUILD.gn
scripts/test.py
src/win/http.cpp

Implement http::get(). Run more tests.

Support more in Windows

---

include/glfw/video-driver.hpp
include/mac/video-driver.hpp
include/video/offscreen-driver.hpp
include/video/opengl-driver.hpp
src/glfw/video-driver.cpp
src/mac/video-driver.cpp
src/video/offscreen-driver.cpp
src/video/opengl-driver.cpp

Try both OpenGL 3.2 and 2.0 in GLFWVideoDriver

---

src/glfw/video-driver.cpp

Remove code to turn maximize into fullscreen

---

.drone.yml
BUILD.gn
Makefile
build/BUILD.gn
build/BUILDCONFIG.gn
configure
scripts/gen-install.py

Support {CPP,C,CXX,LD}FLAGS environment variables

---

.drone.yml
Makefile
configure
scripts/deps.py

Example: 
NINJA=samu ./configure
make
Fixes #353

Support overriding tools in ./configure

---

include/data/plugin.hpp
src/data/level.cpp
src/data/plugin.cpp

Check for duplicate chapters strictly

---

scripts/release

Fixes version numbers for HEAD releases.

Merge releases back to master

---

src/mac/c/CocoaVideoDriver.m

Restore handling of right and center mouse buttons

---

configure

Allow missing cfg module when importing deps

---

.travis.yml

Use Xcode 12.2 on Travis

---

.travis.yml
build/BUILD.gn
build/BUILDCONFIG.gn

Build universal binary on mac

---

.drone.yml
scripts/gen-install.py

Fix installation script

---

src/game/player-ship.cpp

Use shortcut for half zoom, not double zoom

---

.gitmodules

Add OpenGL headers from Mesa for Windows build.

Add Mesa GL headers for Windows build

---

.gitignore
.gn
BUILD.gn
build/BUILDCONFIG.gn
configure
include/win/offscreen.hpp
make-msvc.bat
src/config/win-dirs.cpp
src/glfw/video-driver.cpp
src/video/opengl-dynamic.cpp
src/win/offscreen.cpp

Adds rudimentary native Windows compilation code path.
Fix configure script crash when running `python configure` in current directory.

Add Windows build

---

src/config/file-prefs-driver.cpp
src/config/ledger.cpp
src/drawing/pix-table.cpp

* Integrate ext/libsfz 6864d17
* Integrate ext/procyon 2e4de2f

Integrate ext/{libsfz,procyon}

---

BUILD.gn
include/sound/xaudio2-driver.hpp
src/glfw/main.cpp
src/sound/xaudio2-driver.cpp

Fixes https://github.com/arescentral/antares/issues/322 (take two)

XAudio2 audio driver

---

src/video/glsl/fragment.frag

Fixes #399 
Mostly increases brightness.
Before: 
After:

Apple RGB to sRGB color conversion

---

BUILD.gn
src/glfw/main-win32.cpp

Update Procyon, switch to Windows subsystem instead of console in optimized build and add WinMain.

Don't use console in Windows optimized build.

---

src/sound/xaudio2-driver.cpp

Fixes #407 
Apparently if you submit a buffer in the OnBufferEnd callback when the callback is triggered from FlushSourceBuffers, then the submitted buffers are dequeued immediately instead of played.
Changed to just use normal commands and only do refcount cleanup in the callback.

Rework XAudio2 interrupt/looping behavior

---

src/data/audio.cpp

Change instrument resampling mode to nearest

---

src/game/player-ship.cpp

Don’t use no-ships text if it is absent

---

.github/workflows/ci.yaml
BUILD.gn
doc/packaging.rst
scripts/gen-install.py
src/bin/download-sounds.cpp

Rename install-data to download-sounds

---

include/ui/screens/options.hpp
src/ui/screens/options.cpp

There is currently a "fullscreen" option that can only be configured via `$HOME/.local/share/games/antares/config.pn`. This PR adds an option screen where fullscreen can be controlled from the in-game settings.
For more screenshots and the companion PR to the data repo, see https://github.com/arescentral/antares-data/pull/1

ui/screens/options: add VideoControlScreen & fullscreen option

---

src/game/player-ship.cpp

Handle all multi-clicks as selection events

---

README.rst

If the links end with a slash they lead to a 404 page

Fix URLs in README.rst

---

Makefile
scripts/test.py

Handle a file instead of a symlink in Makefile and scripts/test.py

Create out/cur file on Windows
